on:
  push:
    tags:
      - 'release/android/library/**'

name: Build android libraries from Flutter Module

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.17.5'

      - name: install dependencies
        working-direcory: ./flutter_module
        run: flutter pub get

      - name: run flutter tests
        working-direcory: ./flutter_module
        run: flutter test

      - name: build aar files
        working-direcory: ./flutter_module
        run: flutter build aar --build-number=0.0.1 #This number should be generated dynamically

      - name: push apks to Releases
        working-direcory: ./flutter_module
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/host/outputs/repo"
          token: ${{ secrets.TOKEN }}
