on:
  push:
    tags:
      - 'release/library/android/**'

name: Build android libraries from Flutter Module

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.17.5'

      - name: install dependencies
        working-directory: ./flutter_module
        run: flutter pub get

      - name: run flutter tests
        working-directory: ./flutter_module
        run: flutter test

      - name: build aar files
        working-directory: ./flutter_module
        run: flutter build aar --build-number=0.0.1 #This number should be generated dynamically

      # This is an extra step, is used to zip the repo folder and upload it to releases section in
      # github
      - name: zip repo folder
        working-directory: ./flutter_module
        run: zip -r build/host/outputs/repo.zip build/host/outputs/repo

      # Here we should update our repo folder to a repository server
      - name: push repo folder to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "flutter_module/build/host/outputs/repo.zip"
          token: ${{ secrets.TOKEN }}
